# This is the Role/RoleBinding associated with the user
# that we have associated with the IAM role that this
# repo impersonates via OIDC to deploy.
# Association created with:
#   eksctl create iamidentitymapping \
#     --cluster aws-tenant \
#     --arn arn:aws:iam::979992218380:role/eks-demo-deployer \
#     --username dev-user

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role
rules:
- apiGroups:
    - "apps"
  resources:
    - "deployments"
  verbs:
    - "create"
    - "get"
    - "list"
    - "patch"
    - "update"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-role-binding
subjects:
- kind: User
  name: dev-user
roleRef:
  kind: Role
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
