name: Release Latest Changes

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      AWS_ACCOUNT: 979992218380
      AWS_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install eksctl
        run: |
          # Download eksctl and verify the checksum is what we expect.
          wget https://github.com/weaveworks/eksctl/releases/download/v0.79.0/eksctl_Linux_amd64.tar.gz
          cat eksctl_Linux_amd64.tar.gz | sha256sum -c EKSCTL-CHECKSUM
          tar xzf eksctl_Linux_amd64.tar.gz
          sudo mv /tmp/eksctl /usr/local/bin
          rm eksctl_Linux_amd64.tar.gz

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: push-step
        uses: docker/build-push-action@master
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/eks-demo-deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect to cluster via eksctl
        run: |
          eksctl utils write-kubeconfig --cluster=aws-tenant
          kubectl get deploy
