name: Release Latest Changes

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    env:
      AWS_ACCOUNT: 979992218380
      AWS_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into ghcr.io
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        id: build-and-push
        uses: docker/build-push-action@master
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest


      - name: Install cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.1'

      - name: Sign the container image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ghcr.io/${{ github.repository }}@${{ steps.build-and-push.outputs.digest }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT }}:role/eks-demo-deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Connect to cluster and deploy
        run: |
          aws eks update-kubeconfig --name aws-tenant

          echo Deploying ghcr.io/${{ github.repository }}@${{ steps.build-and-push.outputs.digest }}
          kubectl set image deployment/example-deployment app=ghcr.io/${{ github.repository }}@${{ steps.build-and-push.outputs.digest }}

